# -*- coding: utf-8 -*-
"""json practice(krx).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uISA985w0cx-tQIi2HsZ2e98dx9BiXLg
"""

# 모듈 설치

import json
import requests

def etfTitle():
  url =  'http://data.krx.co.kr/comm/bldAttendant/getJsonData.cmd'
  headers = { 'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
        'Host': 'data.krx.co.kr',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36',
        'Content-Length' : '<calculated when request is sent>'}
  data = 'locale=ko_KR&mktsel=ETF&searchText=&bld=dbms%2Fcomm%2Ffinder%2Ffinder_secuprodisu'
  res = requests.post(url,headers=headers,data=data)
  KrxResult = json.loads(res.text)['block1']
  length = len(KrxResult)
  
  print('길이 : ' + str(length))
  
  KrxList = []
  
  for i in range(0,length):
    
    KrxTitleInformation = {
      'isinCode' : KrxResult[i]['full_code'],
      'tickerSymbol' : KrxResult[i]['short_code'],
      'tickerName' : KrxResult[i]['codeName'],
      }
      
    KrxList.append(KrxTitleInformation)
    
  return KrxList

KrxList







